version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "cd ../ && sh start.sh"
    image: server
    ports:
        - "3000:3000"
    depends_on: 
        - db