version: "3.9"
services:
  db:
    image: postgres:12.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: game
  redis:
    image: redis:latest
    command: redis-server
  web:
    build: .
    command: bash -c "cd ../ && sh start.sh"
    image: server
    ports:
        - "3000:3000"
    depends_on: 
        - db
        - redis
    environment:
      FT_ID: e36c8f337d084b93234fcc6457206c5809c2db9d9263899c2c1d48655826d786 
      FT_SECRET: cf3ab21de3b3abb632c1d189474bb6895c2bf9918a158b5f5e76020868c7865b
    deploy:
      restart_policy:
        condition: on-failure
